// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        (unknown)
// source: pkg/protocol/metrics.proto

package protocol

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// AggregationTemporality tells the backend how to compute rates.
// Without it, rate() semantics are ambiguous — this is why OTLP makes
// it mandatory on Sum.
type AggregationTemporality int32

const (
	AggregationTemporality_AGGREGATION_TEMPORALITY_UNSPECIFIED AggregationTemporality = 0
	AggregationTemporality_AGGREGATION_TEMPORALITY_DELTA       AggregationTemporality = 1
	AggregationTemporality_AGGREGATION_TEMPORALITY_CUMULATIVE  AggregationTemporality = 2
)

// Enum value maps for AggregationTemporality.
var (
	AggregationTemporality_name = map[int32]string{
		0: "AGGREGATION_TEMPORALITY_UNSPECIFIED",
		1: "AGGREGATION_TEMPORALITY_DELTA",
		2: "AGGREGATION_TEMPORALITY_CUMULATIVE",
	}
	AggregationTemporality_value = map[string]int32{
		"AGGREGATION_TEMPORALITY_UNSPECIFIED": 0,
		"AGGREGATION_TEMPORALITY_DELTA":       1,
		"AGGREGATION_TEMPORALITY_CUMULATIVE":  2,
	}
)

func (x AggregationTemporality) Enum() *AggregationTemporality {
	p := new(AggregationTemporality)
	*p = x
	return p
}

func (x AggregationTemporality) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (AggregationTemporality) Descriptor() protoreflect.EnumDescriptor {
	return file_pkg_protocol_metrics_proto_enumTypes[0].Descriptor()
}

func (AggregationTemporality) Type() protoreflect.EnumType {
	return &file_pkg_protocol_metrics_proto_enumTypes[0]
}

func (x AggregationTemporality) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use AggregationTemporality.Descriptor instead.
func (AggregationTemporality) EnumDescriptor() ([]byte, []int) {
	return file_pkg_protocol_metrics_proto_rawDescGZIP(), []int{0}
}

// ExportMetricsRequest is the top-level wire message sent by the agent.
type ExportMetricsRequest struct {
	state        protoimpl.MessageState `protogen:"open.v1"`
	Resource     *Resource              `protobuf:"bytes,1,opt,name=resource,proto3" json:"resource,omitempty"`
	ScopeMetrics []*ScopeMetrics        `protobuf:"bytes,2,rep,name=scope_metrics,json=scopeMetrics,proto3" json:"scope_metrics,omitempty"`
	// Agent-side wall clock when this batch was assembled.
	ExportTimeUnixNano int64 `protobuf:"varint,3,opt,name=export_time_unix_nano,json=exportTimeUnixNano,proto3" json:"export_time_unix_nano,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *ExportMetricsRequest) Reset() {
	*x = ExportMetricsRequest{}
	mi := &file_pkg_protocol_metrics_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExportMetricsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExportMetricsRequest) ProtoMessage() {}

func (x *ExportMetricsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_protocol_metrics_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExportMetricsRequest.ProtoReflect.Descriptor instead.
func (*ExportMetricsRequest) Descriptor() ([]byte, []int) {
	return file_pkg_protocol_metrics_proto_rawDescGZIP(), []int{0}
}

func (x *ExportMetricsRequest) GetResource() *Resource {
	if x != nil {
		return x.Resource
	}
	return nil
}

func (x *ExportMetricsRequest) GetScopeMetrics() []*ScopeMetrics {
	if x != nil {
		return x.ScopeMetrics
	}
	return nil
}

func (x *ExportMetricsRequest) GetExportTimeUnixNano() int64 {
	if x != nil {
		return x.ExportTimeUnixNano
	}
	return 0
}

type ExportMetricsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	AcceptedCount int32                  `protobuf:"varint,3,opt,name=accepted_count,json=acceptedCount,proto3" json:"accepted_count,omitempty"`
	RejectedCount int32                  `protobuf:"varint,4,opt,name=rejected_count,json=rejectedCount,proto3" json:"rejected_count,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ExportMetricsResponse) Reset() {
	*x = ExportMetricsResponse{}
	mi := &file_pkg_protocol_metrics_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExportMetricsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExportMetricsResponse) ProtoMessage() {}

func (x *ExportMetricsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_protocol_metrics_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExportMetricsResponse.ProtoReflect.Descriptor instead.
func (*ExportMetricsResponse) Descriptor() ([]byte, []int) {
	return file_pkg_protocol_metrics_proto_rawDescGZIP(), []int{1}
}

func (x *ExportMetricsResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *ExportMetricsResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *ExportMetricsResponse) GetAcceptedCount() int32 {
	if x != nil {
		return x.AcceptedCount
	}
	return 0
}

func (x *ExportMetricsResponse) GetRejectedCount() int32 {
	if x != nil {
		return x.RejectedCount
	}
	return 0
}

// Resource describes the entity producing the metrics (the edge agent).
type Resource struct {
	state   protoimpl.MessageState `protogen:"open.v1"`
	AgentId string                 `protobuf:"bytes,1,opt,name=agent_id,json=agentId,proto3" json:"agent_id,omitempty"`
	// Low-cardinality attributes only (e.g. host.name). High-cardinality
	// values such as connection_id are forbidden (tag/field discipline).
	Attributes    map[string]string `protobuf:"bytes,2,rep,name=attributes,proto3" json:"attributes,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Resource) Reset() {
	*x = Resource{}
	mi := &file_pkg_protocol_metrics_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Resource) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Resource) ProtoMessage() {}

func (x *Resource) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_protocol_metrics_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Resource.ProtoReflect.Descriptor instead.
func (*Resource) Descriptor() ([]byte, []int) {
	return file_pkg_protocol_metrics_proto_rawDescGZIP(), []int{2}
}

func (x *Resource) GetAgentId() string {
	if x != nil {
		return x.AgentId
	}
	return ""
}

func (x *Resource) GetAttributes() map[string]string {
	if x != nil {
		return x.Attributes
	}
	return nil
}

// InstrumentationScope identifies the producing plugin.
type InstrumentationScope struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"` // plugin name, e.g. "cpu", "ebpf"
	Version       string                 `protobuf:"bytes,2,opt,name=version,proto3" json:"version,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *InstrumentationScope) Reset() {
	*x = InstrumentationScope{}
	mi := &file_pkg_protocol_metrics_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InstrumentationScope) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InstrumentationScope) ProtoMessage() {}

func (x *InstrumentationScope) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_protocol_metrics_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InstrumentationScope.ProtoReflect.Descriptor instead.
func (*InstrumentationScope) Descriptor() ([]byte, []int) {
	return file_pkg_protocol_metrics_proto_rawDescGZIP(), []int{3}
}

func (x *InstrumentationScope) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *InstrumentationScope) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

// ScopeMetrics groups metrics produced by the same plugin.
type ScopeMetrics struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Scope         *InstrumentationScope  `protobuf:"bytes,1,opt,name=scope,proto3" json:"scope,omitempty"`
	Metrics       []*Metric              `protobuf:"bytes,2,rep,name=metrics,proto3" json:"metrics,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ScopeMetrics) Reset() {
	*x = ScopeMetrics{}
	mi := &file_pkg_protocol_metrics_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ScopeMetrics) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ScopeMetrics) ProtoMessage() {}

func (x *ScopeMetrics) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_protocol_metrics_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ScopeMetrics.ProtoReflect.Descriptor instead.
func (*ScopeMetrics) Descriptor() ([]byte, []int) {
	return file_pkg_protocol_metrics_proto_rawDescGZIP(), []int{4}
}

func (x *ScopeMetrics) GetScope() *InstrumentationScope {
	if x != nil {
		return x.Scope
	}
	return nil
}

func (x *ScopeMetrics) GetMetrics() []*Metric {
	if x != nil {
		return x.Metrics
	}
	return nil
}

// Metric carries exactly one typed data stream.
type Metric struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	Name  string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	// UCUM unit annotation, e.g. "1" (ratio), "By" (bytes), "{packet}".
	Unit        string `protobuf:"bytes,2,opt,name=unit,proto3" json:"unit,omitempty"`
	Description string `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	// Types that are valid to be assigned to Data:
	//
	//	*Metric_Gauge
	//	*Metric_Sum
	//	*Metric_Histogram
	Data          isMetric_Data `protobuf_oneof:"data"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Metric) Reset() {
	*x = Metric{}
	mi := &file_pkg_protocol_metrics_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Metric) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Metric) ProtoMessage() {}

func (x *Metric) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_protocol_metrics_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Metric.ProtoReflect.Descriptor instead.
func (*Metric) Descriptor() ([]byte, []int) {
	return file_pkg_protocol_metrics_proto_rawDescGZIP(), []int{5}
}

func (x *Metric) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Metric) GetUnit() string {
	if x != nil {
		return x.Unit
	}
	return ""
}

func (x *Metric) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *Metric) GetData() isMetric_Data {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *Metric) GetGauge() *Gauge {
	if x != nil {
		if x, ok := x.Data.(*Metric_Gauge); ok {
			return x.Gauge
		}
	}
	return nil
}

func (x *Metric) GetSum() *Sum {
	if x != nil {
		if x, ok := x.Data.(*Metric_Sum); ok {
			return x.Sum
		}
	}
	return nil
}

func (x *Metric) GetHistogram() *Histogram {
	if x != nil {
		if x, ok := x.Data.(*Metric_Histogram); ok {
			return x.Histogram
		}
	}
	return nil
}

type isMetric_Data interface {
	isMetric_Data()
}

type Metric_Gauge struct {
	Gauge *Gauge `protobuf:"bytes,4,opt,name=gauge,proto3,oneof"`
}

type Metric_Sum struct {
	Sum *Sum `protobuf:"bytes,5,opt,name=sum,proto3,oneof"`
}

type Metric_Histogram struct {
	Histogram *Histogram `protobuf:"bytes,6,opt,name=histogram,proto3,oneof"`
}

func (*Metric_Gauge) isMetric_Data() {}

func (*Metric_Sum) isMetric_Data() {}

func (*Metric_Histogram) isMetric_Data() {}

type Gauge struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	DataPoints    []*NumberDataPoint     `protobuf:"bytes,1,rep,name=data_points,json=dataPoints,proto3" json:"data_points,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Gauge) Reset() {
	*x = Gauge{}
	mi := &file_pkg_protocol_metrics_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Gauge) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Gauge) ProtoMessage() {}

func (x *Gauge) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_protocol_metrics_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Gauge.ProtoReflect.Descriptor instead.
func (*Gauge) Descriptor() ([]byte, []int) {
	return file_pkg_protocol_metrics_proto_rawDescGZIP(), []int{6}
}

func (x *Gauge) GetDataPoints() []*NumberDataPoint {
	if x != nil {
		return x.DataPoints
	}
	return nil
}

type Sum struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	DataPoints    []*NumberDataPoint     `protobuf:"bytes,1,rep,name=data_points,json=dataPoints,proto3" json:"data_points,omitempty"`
	Temporality   AggregationTemporality `protobuf:"varint,2,opt,name=temporality,proto3,enum=protocol.AggregationTemporality" json:"temporality,omitempty"`
	IsMonotonic   bool                   `protobuf:"varint,3,opt,name=is_monotonic,json=isMonotonic,proto3" json:"is_monotonic,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Sum) Reset() {
	*x = Sum{}
	mi := &file_pkg_protocol_metrics_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Sum) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Sum) ProtoMessage() {}

func (x *Sum) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_protocol_metrics_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Sum.ProtoReflect.Descriptor instead.
func (*Sum) Descriptor() ([]byte, []int) {
	return file_pkg_protocol_metrics_proto_rawDescGZIP(), []int{7}
}

func (x *Sum) GetDataPoints() []*NumberDataPoint {
	if x != nil {
		return x.DataPoints
	}
	return nil
}

func (x *Sum) GetTemporality() AggregationTemporality {
	if x != nil {
		return x.Temporality
	}
	return AggregationTemporality_AGGREGATION_TEMPORALITY_UNSPECIFIED
}

func (x *Sum) GetIsMonotonic() bool {
	if x != nil {
		return x.IsMonotonic
	}
	return false
}

// Histogram stores bucket counts instead of raw samples: constant space
// and cross-instance aggregability (Monarch distribution / OTLP Histogram).
type Histogram struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	DataPoints    []*HistogramDataPoint  `protobuf:"bytes,1,rep,name=data_points,json=dataPoints,proto3" json:"data_points,omitempty"`
	Temporality   AggregationTemporality `protobuf:"varint,2,opt,name=temporality,proto3,enum=protocol.AggregationTemporality" json:"temporality,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Histogram) Reset() {
	*x = Histogram{}
	mi := &file_pkg_protocol_metrics_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Histogram) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Histogram) ProtoMessage() {}

func (x *Histogram) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_protocol_metrics_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Histogram.ProtoReflect.Descriptor instead.
func (*Histogram) Descriptor() ([]byte, []int) {
	return file_pkg_protocol_metrics_proto_rawDescGZIP(), []int{8}
}

func (x *Histogram) GetDataPoints() []*HistogramDataPoint {
	if x != nil {
		return x.DataPoints
	}
	return nil
}

func (x *Histogram) GetTemporality() AggregationTemporality {
	if x != nil {
		return x.Temporality
	}
	return AggregationTemporality_AGGREGATION_TEMPORALITY_UNSPECIFIED
}

type NumberDataPoint struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Per-series attributes; keep cardinality low.
	Attributes    map[string]string `protobuf:"bytes,1,rep,name=attributes,proto3" json:"attributes,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	TimeUnixNano  int64             `protobuf:"varint,2,opt,name=time_unix_nano,json=timeUnixNano,proto3" json:"time_unix_nano,omitempty"`
	Value         float64           `protobuf:"fixed64,3,opt,name=value,proto3" json:"value,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NumberDataPoint) Reset() {
	*x = NumberDataPoint{}
	mi := &file_pkg_protocol_metrics_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NumberDataPoint) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NumberDataPoint) ProtoMessage() {}

func (x *NumberDataPoint) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_protocol_metrics_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NumberDataPoint.ProtoReflect.Descriptor instead.
func (*NumberDataPoint) Descriptor() ([]byte, []int) {
	return file_pkg_protocol_metrics_proto_rawDescGZIP(), []int{9}
}

func (x *NumberDataPoint) GetAttributes() map[string]string {
	if x != nil {
		return x.Attributes
	}
	return nil
}

func (x *NumberDataPoint) GetTimeUnixNano() int64 {
	if x != nil {
		return x.TimeUnixNano
	}
	return 0
}

func (x *NumberDataPoint) GetValue() float64 {
	if x != nil {
		return x.Value
	}
	return 0
}

type HistogramDataPoint struct {
	state        protoimpl.MessageState `protogen:"open.v1"`
	Attributes   map[string]string      `protobuf:"bytes,1,rep,name=attributes,proto3" json:"attributes,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	TimeUnixNano int64                  `protobuf:"varint,2,opt,name=time_unix_nano,json=timeUnixNano,proto3" json:"time_unix_nano,omitempty"`
	Count        uint64                 `protobuf:"varint,3,opt,name=count,proto3" json:"count,omitempty"`
	Sum          float64                `protobuf:"fixed64,4,opt,name=sum,proto3" json:"sum,omitempty"`
	// bucket_counts[i] counts observations in
	//   (explicit_bounds[i-1], explicit_bounds[i]]; len = len(explicit_bounds)+1.
	BucketCounts   []uint64  `protobuf:"varint,5,rep,packed,name=bucket_counts,json=bucketCounts,proto3" json:"bucket_counts,omitempty"`
	ExplicitBounds []float64 `protobuf:"fixed64,6,rep,packed,name=explicit_bounds,json=explicitBounds,proto3" json:"explicit_bounds,omitempty"`
	Min            float64   `protobuf:"fixed64,7,opt,name=min,proto3" json:"min,omitempty"`
	Max            float64   `protobuf:"fixed64,8,opt,name=max,proto3" json:"max,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *HistogramDataPoint) Reset() {
	*x = HistogramDataPoint{}
	mi := &file_pkg_protocol_metrics_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HistogramDataPoint) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HistogramDataPoint) ProtoMessage() {}

func (x *HistogramDataPoint) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_protocol_metrics_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HistogramDataPoint.ProtoReflect.Descriptor instead.
func (*HistogramDataPoint) Descriptor() ([]byte, []int) {
	return file_pkg_protocol_metrics_proto_rawDescGZIP(), []int{10}
}

func (x *HistogramDataPoint) GetAttributes() map[string]string {
	if x != nil {
		return x.Attributes
	}
	return nil
}

func (x *HistogramDataPoint) GetTimeUnixNano() int64 {
	if x != nil {
		return x.TimeUnixNano
	}
	return 0
}

func (x *HistogramDataPoint) GetCount() uint64 {
	if x != nil {
		return x.Count
	}
	return 0
}

func (x *HistogramDataPoint) GetSum() float64 {
	if x != nil {
		return x.Sum
	}
	return 0
}

func (x *HistogramDataPoint) GetBucketCounts() []uint64 {
	if x != nil {
		return x.BucketCounts
	}
	return nil
}

func (x *HistogramDataPoint) GetExplicitBounds() []float64 {
	if x != nil {
		return x.ExplicitBounds
	}
	return nil
}

func (x *HistogramDataPoint) GetMin() float64 {
	if x != nil {
		return x.Min
	}
	return 0
}

func (x *HistogramDataPoint) GetMax() float64 {
	if x != nil {
		return x.Max
	}
	return 0
}

var File_pkg_protocol_metrics_proto protoreflect.FileDescriptor

const file_pkg_protocol_metrics_proto_rawDesc = "" +
	"\n" +
	"\x1apkg/protocol/metrics.proto\x12\bprotocol\"\xb6\x01\n" +
	"\x14ExportMetricsRequest\x12.\n" +
	"\bresource\x18\x01 \x01(\v2\x12.protocol.ResourceR\bresource\x12;\n" +
	"\rscope_metrics\x18\x02 \x03(\v2\x16.protocol.ScopeMetricsR\fscopeMetrics\x121\n" +
	"\x15export_time_unix_nano\x18\x03 \x01(\x03R\x12exportTimeUnixNano\"\x99\x01\n" +
	"\x15ExportMetricsResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12%\n" +
	"\x0eaccepted_count\x18\x03 \x01(\x05R\racceptedCount\x12%\n" +
	"\x0erejected_count\x18\x04 \x01(\x05R\rrejectedCount\"\xa8\x01\n" +
	"\bResource\x12\x19\n" +
	"\bagent_id\x18\x01 \x01(\tR\aagentId\x12B\n" +
	"\n" +
	"attributes\x18\x02 \x03(\v2\".protocol.Resource.AttributesEntryR\n" +
	"attributes\x1a=\n" +
	"\x0fAttributesEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"D\n" +
	"\x14InstrumentationScope\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x18\n" +
	"\aversion\x18\x02 \x01(\tR\aversion\"p\n" +
	"\fScopeMetrics\x124\n" +
	"\x05scope\x18\x01 \x01(\v2\x1e.protocol.InstrumentationScopeR\x05scope\x12*\n" +
	"\ametrics\x18\x02 \x03(\v2\x10.protocol.MetricR\ametrics\"\xdb\x01\n" +
	"\x06Metric\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x12\n" +
	"\x04unit\x18\x02 \x01(\tR\x04unit\x12 \n" +
	"\vdescription\x18\x03 \x01(\tR\vdescription\x12'\n" +
	"\x05gauge\x18\x04 \x01(\v2\x0f.protocol.GaugeH\x00R\x05gauge\x12!\n" +
	"\x03sum\x18\x05 \x01(\v2\r.protocol.SumH\x00R\x03sum\x123\n" +
	"\thistogram\x18\x06 \x01(\v2\x13.protocol.HistogramH\x00R\thistogramB\x06\n" +
	"\x04data\"C\n" +
	"\x05Gauge\x12:\n" +
	"\vdata_points\x18\x01 \x03(\v2\x19.protocol.NumberDataPointR\n" +
	"dataPoints\"\xa8\x01\n" +
	"\x03Sum\x12:\n" +
	"\vdata_points\x18\x01 \x03(\v2\x19.protocol.NumberDataPointR\n" +
	"dataPoints\x12B\n" +
	"\vtemporality\x18\x02 \x01(\x0e2 .protocol.AggregationTemporalityR\vtemporality\x12!\n" +
	"\fis_monotonic\x18\x03 \x01(\bR\visMonotonic\"\x8e\x01\n" +
	"\tHistogram\x12=\n" +
	"\vdata_points\x18\x01 \x03(\v2\x1c.protocol.HistogramDataPointR\n" +
	"dataPoints\x12B\n" +
	"\vtemporality\x18\x02 \x01(\x0e2 .protocol.AggregationTemporalityR\vtemporality\"\xd7\x01\n" +
	"\x0fNumberDataPoint\x12I\n" +
	"\n" +
	"attributes\x18\x01 \x03(\v2).protocol.NumberDataPoint.AttributesEntryR\n" +
	"attributes\x12$\n" +
	"\x0etime_unix_nano\x18\x02 \x01(\x03R\ftimeUnixNano\x12\x14\n" +
	"\x05value\x18\x03 \x01(\x01R\x05value\x1a=\n" +
	"\x0fAttributesEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\xe1\x02\n" +
	"\x12HistogramDataPoint\x12L\n" +
	"\n" +
	"attributes\x18\x01 \x03(\v2,.protocol.HistogramDataPoint.AttributesEntryR\n" +
	"attributes\x12$\n" +
	"\x0etime_unix_nano\x18\x02 \x01(\x03R\ftimeUnixNano\x12\x14\n" +
	"\x05count\x18\x03 \x01(\x04R\x05count\x12\x10\n" +
	"\x03sum\x18\x04 \x01(\x01R\x03sum\x12#\n" +
	"\rbucket_counts\x18\x05 \x03(\x04R\fbucketCounts\x12'\n" +
	"\x0fexplicit_bounds\x18\x06 \x03(\x01R\x0eexplicitBounds\x12\x10\n" +
	"\x03min\x18\a \x01(\x01R\x03min\x12\x10\n" +
	"\x03max\x18\b \x01(\x01R\x03max\x1a=\n" +
	"\x0fAttributesEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01*\x8c\x01\n" +
	"\x16AggregationTemporality\x12'\n" +
	"#AGGREGATION_TEMPORALITY_UNSPECIFIED\x10\x00\x12!\n" +
	"\x1dAGGREGATION_TEMPORALITY_DELTA\x10\x01\x12&\n" +
	"\"AGGREGATION_TEMPORALITY_CUMULATIVE\x10\x022e\n" +
	"\x0eMetricsService\x12S\n" +
	"\x10SendBatchMetrics\x12\x1e.protocol.ExportMetricsRequest\x1a\x1f.protocol.ExportMetricsResponseB+Z)github.com/konpure/Kon-Agent/pkg/protocolb\x06proto3"

var (
	file_pkg_protocol_metrics_proto_rawDescOnce sync.Once
	file_pkg_protocol_metrics_proto_rawDescData []byte
)

func file_pkg_protocol_metrics_proto_rawDescGZIP() []byte {
	file_pkg_protocol_metrics_proto_rawDescOnce.Do(func() {
		file_pkg_protocol_metrics_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_pkg_protocol_metrics_proto_rawDesc), len(file_pkg_protocol_metrics_proto_rawDesc)))
	})
	return file_pkg_protocol_metrics_proto_rawDescData
}

var file_pkg_protocol_metrics_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_pkg_protocol_metrics_proto_msgTypes = make([]protoimpl.MessageInfo, 14)
var file_pkg_protocol_metrics_proto_goTypes = []any{
	(AggregationTemporality)(0),   // 0: protocol.AggregationTemporality
	(*ExportMetricsRequest)(nil),  // 1: protocol.ExportMetricsRequest
	(*ExportMetricsResponse)(nil), // 2: protocol.ExportMetricsResponse
	(*Resource)(nil),              // 3: protocol.Resource
	(*InstrumentationScope)(nil),  // 4: protocol.InstrumentationScope
	(*ScopeMetrics)(nil),          // 5: protocol.ScopeMetrics
	(*Metric)(nil),                // 6: protocol.Metric
	(*Gauge)(nil),                 // 7: protocol.Gauge
	(*Sum)(nil),                   // 8: protocol.Sum
	(*Histogram)(nil),             // 9: protocol.Histogram
	(*NumberDataPoint)(nil),       // 10: protocol.NumberDataPoint
	(*HistogramDataPoint)(nil),    // 11: protocol.HistogramDataPoint
	nil,                           // 12: protocol.Resource.AttributesEntry
	nil,                           // 13: protocol.NumberDataPoint.AttributesEntry
	nil,                           // 14: protocol.HistogramDataPoint.AttributesEntry
}
var file_pkg_protocol_metrics_proto_depIdxs = []int32{
	3,  // 0: protocol.ExportMetricsRequest.resource:type_name -> protocol.Resource
	5,  // 1: protocol.ExportMetricsRequest.scope_metrics:type_name -> protocol.ScopeMetrics
	12, // 2: protocol.Resource.attributes:type_name -> protocol.Resource.AttributesEntry
	4,  // 3: protocol.ScopeMetrics.scope:type_name -> protocol.InstrumentationScope
	6,  // 4: protocol.ScopeMetrics.metrics:type_name -> protocol.Metric
	7,  // 5: protocol.Metric.gauge:type_name -> protocol.Gauge
	8,  // 6: protocol.Metric.sum:type_name -> protocol.Sum
	9,  // 7: protocol.Metric.histogram:type_name -> protocol.Histogram
	10, // 8: protocol.Gauge.data_points:type_name -> protocol.NumberDataPoint
	10, // 9: protocol.Sum.data_points:type_name -> protocol.NumberDataPoint
	0,  // 10: protocol.Sum.temporality:type_name -> protocol.AggregationTemporality
	11, // 11: protocol.Histogram.data_points:type_name -> protocol.HistogramDataPoint
	0,  // 12: protocol.Histogram.temporality:type_name -> protocol.AggregationTemporality
	13, // 13: protocol.NumberDataPoint.attributes:type_name -> protocol.NumberDataPoint.AttributesEntry
	14, // 14: protocol.HistogramDataPoint.attributes:type_name -> protocol.HistogramDataPoint.AttributesEntry
	1,  // 15: protocol.MetricsService.SendBatchMetrics:input_type -> protocol.ExportMetricsRequest
	2,  // 16: protocol.MetricsService.SendBatchMetrics:output_type -> protocol.ExportMetricsResponse
	16, // [16:17] is the sub-list for method output_type
	15, // [15:16] is the sub-list for method input_type
	15, // [15:15] is the sub-list for extension type_name
	15, // [15:15] is the sub-list for extension extendee
	0,  // [0:15] is the sub-list for field type_name
}

func init() { file_pkg_protocol_metrics_proto_init() }
func file_pkg_protocol_metrics_proto_init() {
	if File_pkg_protocol_metrics_proto != nil {
		return
	}
	file_pkg_protocol_metrics_proto_msgTypes[5].OneofWrappers = []any{
		(*Metric_Gauge)(nil),
		(*Metric_Sum)(nil),
		(*Metric_Histogram)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_pkg_protocol_metrics_proto_rawDesc), len(file_pkg_protocol_metrics_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   14,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_pkg_protocol_metrics_proto_goTypes,
		DependencyIndexes: file_pkg_protocol_metrics_proto_depIdxs,
		EnumInfos:         file_pkg_protocol_metrics_proto_enumTypes,
		MessageInfos:      file_pkg_protocol_metrics_proto_msgTypes,
	}.Build()
	File_pkg_protocol_metrics_proto = out.File
	file_pkg_protocol_metrics_proto_goTypes = nil
	file_pkg_protocol_metrics_proto_depIdxs = nil
}
