// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.7
// 	protoc        v3.21.12
// source: pkg/protocol/metrics.proto

package protocol

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Metric struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Timestamp     int64                  `protobuf:"varint,1,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Value         float64                `protobuf:"fixed64,3,opt,name=value,proto3" json:"value,omitempty"`
	Labels        map[string]string      `protobuf:"bytes,4,rep,name=labels,proto3" json:"labels,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Metric) Reset() {
	*x = Metric{}
	mi := &file_pkg_protocol_metrics_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Metric) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Metric) ProtoMessage() {}

func (x *Metric) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_protocol_metrics_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Metric.ProtoReflect.Descriptor instead.
func (*Metric) Descriptor() ([]byte, []int) {
	return file_pkg_protocol_metrics_proto_rawDescGZIP(), []int{0}
}

func (x *Metric) GetTimestamp() int64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

func (x *Metric) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Metric) GetValue() float64 {
	if x != nil {
		return x.Value
	}
	return 0
}

func (x *Metric) GetLabels() map[string]string {
	if x != nil {
		return x.Labels
	}
	return nil
}

var File_pkg_protocol_metrics_proto protoreflect.FileDescriptor

const file_pkg_protocol_metrics_proto_rawDesc = "" +
	"\n" +
	"\x1apkg/protocol/metrics.proto\x12\ametrics\"\xc0\x01\n" +
	"\x06Metric\x12\x1c\n" +
	"\ttimestamp\x18\x01 \x01(\x03R\ttimestamp\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x14\n" +
	"\x05value\x18\x03 \x01(\x01R\x05value\x123\n" +
	"\x06labels\x18\x04 \x03(\v2\x1b.metrics.Metric.LabelsEntryR\x06labels\x1a9\n" +
	"\vLabelsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01B+Z)github.com/konpure/Kon-Agent/pkg/protocolb\x06proto3"

var (
	file_pkg_protocol_metrics_proto_rawDescOnce sync.Once
	file_pkg_protocol_metrics_proto_rawDescData []byte
)

func file_pkg_protocol_metrics_proto_rawDescGZIP() []byte {
	file_pkg_protocol_metrics_proto_rawDescOnce.Do(func() {
		file_pkg_protocol_metrics_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_pkg_protocol_metrics_proto_rawDesc), len(file_pkg_protocol_metrics_proto_rawDesc)))
	})
	return file_pkg_protocol_metrics_proto_rawDescData
}

var file_pkg_protocol_metrics_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_pkg_protocol_metrics_proto_goTypes = []any{
	(*Metric)(nil), // 0: metrics.Metric
	nil,            // 1: metrics.Metric.LabelsEntry
}
var file_pkg_protocol_metrics_proto_depIdxs = []int32{
	1, // 0: metrics.Metric.labels:type_name -> metrics.Metric.LabelsEntry
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_pkg_protocol_metrics_proto_init() }
func file_pkg_protocol_metrics_proto_init() {
	if File_pkg_protocol_metrics_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_pkg_protocol_metrics_proto_rawDesc), len(file_pkg_protocol_metrics_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_pkg_protocol_metrics_proto_goTypes,
		DependencyIndexes: file_pkg_protocol_metrics_proto_depIdxs,
		MessageInfos:      file_pkg_protocol_metrics_proto_msgTypes,
	}.Build()
	File_pkg_protocol_metrics_proto = out.File
	file_pkg_protocol_metrics_proto_goTypes = nil
	file_pkg_protocol_metrics_proto_depIdxs = nil
}
